name: suid-wrapper
base: core20
version: '0.1.4'
summary: Utility to create binary executables to be used with the suid flag
description: |
  This utility lets you create an executable binary, with the suid flag set.
  The suid flag makes it possible for an user to execute an executable as
  if they are the owner of the file. For example:

    suid-wrapper -o run_docker_sh $(which docker) -- run -it --rm alpine sh --

  With the command above, a run_docker_sh will be created. Consider this file
  is owned by a user named 'docker'. If a user named 'user' tries to run it,
  because of the suid flag, the process that will be started will have the
  uid set to that of 'docker', with the same permissions 'docker' has.

grade: stable
confinement: strict
apps:
  suid-wrapper:
    command: bin/suid-wrapper
    plugs:
      - home
parts:
  suid-wrapper:
    plugin: nil
    source: https://github.com/thiagorb/suid-wrapper
    source-type: git
    build-packages:
      - make
    override-build: |
      APP_VERSION=0.1.4 make release
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp bin/release/suid-wrapper $SNAPCRAFT_PART_INSTALL/bin/suid-wrapper
